import { Component, OnInit } from '@angular/core';
import { environment } from '@src/environments/environment';

@Component({
  selector: 'app-info',
  templateUrl: './info.component.html',
  styleUrls: ['./info.component.scss']
})
export class InfoComponent implements OnInit {

  constructor() { }

  links: { href: string, title: string }[] = [
    { href: 'http://github.com/alexbyk/dummycoin', title: 'Github repo and detailed specifications' },
    { href: `${environment.docsBase}/api`, title: 'GRPC api documentation (autogenerated)' },
    { href: `${environment.docsBase}/node`, title: 'Nodejs documentation (autogenerated)' },
    { href: `${environment.docsBase}/front`, title: 'Angular documentation (autogenerated)' },
  ];

  ngOnInit() {
  }

}
